name: markdown_toc
description: Table of contents generator for Markdown files.
version: 1.1.0
homepage: https://github.com/hoylen/markdown_toc

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
