name: markdown_toc
description: Utility to number headings and generate Table of contents for Markdown files.
version: 1.1.1
homepage: https://github.com/hoylen/markdown_toc

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  pana: ^0.21.27

executables:
  markdown_toc:

